In [45]:
#import pandas
import pandas as pd

In [46]:
#Import pickle and pickle file named customer_id_merged.pkl
import pickle
df = pickle.load(open("customer_id_merged.pkl", "rb"))

#Print the first 5 rows of the dataframe
print(df.head())

             customer_age   Recency  average_product_price  chain_percentage  \
customer_id
5d272b9dcb      -1.463397  2.699634               0.499788          0.957495
f6d1b2ba63       1.490629  2.699634              -0.734841          0.957495
180c632ed8      -0.619389  2.656542               0.725499         -0.334027
4eb37a6705      -1.041393  2.656542               0.865613         -1.625548
6aef2b6726       1.771965  2.656542               1.204057         -1.625548

             log_vendor_count  log_order_rate_per_week  \
customer_id
5d272b9dcb          -0.306522                 5.373406
f6d1b2ba63          -1.098006                 5.373406
180c632ed8          -0.306522                 3.731085
4eb37a6705          -0.306522                 3.731085
6aef2b6726          -0.306522                 3.731085

             log_amount_spent_per_week  demographics_labels  \
customer_id
5d272b9dcb                    3.823580                    0
f6d1b2ba63                    2.894886                    0
180c632ed8                    3.574793                    0
4eb37a6705                    4.288361                    0
6aef2b6726                    3.276592                    0

             purchase_behavior_labels  merged_labels
customer_id
5d272b9dcb                          2              0
f6d1b2ba63                          2              0
180c632ed8                          1              0
4eb37a6705                          1              0
6aef2b6726                          1              0

In [47]:
#impor the standard scaler file called standard_scaler.pkl
from sklearn.preprocessing import StandardScaler
scaler = pickle.load(open("standard_scaler.pkl", "rb"))

In [48]:
df.columns

Index(['customer_age', 'Recency', 'average_product_price', 'chain_percentage',
       'log_vendor_count', 'log_order_rate_per_week',
       'log_amount_spent_per_week', 'demographics_labels',
       'purchase_behavior_labels', 'merged_labels'],
      dtype='object')

In [49]:
last_three_columns = ['demographics_labels','purchase_behavior_labels', 'merged_labels']

df_last_three = df[last_three_columns]
df_no_last_three = df.drop(columns=last_three_columns)


#Print the first 5 rows of the dataframe
print(df_no_last_three.head())

             customer_age   Recency  average_product_price  chain_percentage  \
customer_id
5d272b9dcb      -1.463397  2.699634               0.499788          0.957495
f6d1b2ba63       1.490629  2.699634              -0.734841          0.957495
180c632ed8      -0.619389  2.656542               0.725499         -0.334027
4eb37a6705      -1.041393  2.656542               0.865613         -1.625548
6aef2b6726       1.771965  2.656542               1.204057         -1.625548

             log_vendor_count  log_order_rate_per_week  \
customer_id
5d272b9dcb          -0.306522                 5.373406
f6d1b2ba63          -1.098006                 5.373406
180c632ed8          -0.306522                 3.731085
4eb37a6705          -0.306522                 3.731085
6aef2b6726          -0.306522                 3.731085

             log_amount_spent_per_week
customer_id
5d272b9dcb                    3.823580
f6d1b2ba63                    2.894886
180c632ed8                    3.574793
4eb37a6705                    4.288361
6aef2b6726                    3.276592

In [50]:
# Store original column names before transformation
original_columns = df_no_last_three.columns

# Apply the scaler to the dataframe
df_no_last_three = pd.DataFrame(scaler.inverse_transform(df_no_last_three))

# Restore original column names
df_no_last_three.columns = original_columns
df_no_last_three.index = df.index

In [51]:
df_no_last_three.head()

,customer_age,Recency,average_product_price,chain_percentage,log_vendor_count,log_order_rate_per_week,log_amount_spent_per_week
customer_id,,,,,,,
5d272b9dcb,17.0,89.0,9.605,100.0,1.098612,2.708050,4.908750
f6d1b2ba63,38.0,89.0,4.600,100.0,0.693147,2.708050,4.180522
180c632ed8,23.0,88.0,10.520,50.0,1.098612,2.079442,4.713666
4eb37a6705,20.0,88.0,11.088,0.0,1.098612,2.079442,5.273205
6aef2b6726,40.0,88.0,12.460,0.0,1.098612,2.079442,4.479834

In [52]:
#now i want to merge the df_no_last_three and df_last_three
df_merged = pd.concat([df_no_last_three, df_last_three], axis=1)
df_merged.head()

,customer_age,Recency,average_product_price,chain_percentage,log_vendor_count,log_order_rate_per_week,log_amount_spent_per_week,demographics_labels,purchase_behavior_labels,merged_labels
customer_id,,,,,,,,,,
5d272b9dcb,17.0,89.0,9.605,100.0,1.098612,2.708050,4.908750,0,2,0
f6d1b2ba63,38.0,89.0,4.600,100.0,0.693147,2.708050,4.180522,0,2,0
180c632ed8,23.0,88.0,10.520,50.0,1.098612,2.079442,4.713666,0,1,0
4eb37a6705,20.0,88.0,11.088,0.0,1.098612,2.079442,5.273205,0,1,0
6aef2b6726,40.0,88.0,12.460,0.0,1.098612,2.079442,4.479834,0,1,0

In [53]:
#export the dataframe to a pickle file
df_merged.to_pickle("customer_id_merged_unscaled.pkl")